dbt_1:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      schema: "airport_db"
      username: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      ssl_disabled: True
